apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: wordpress-deployment 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: wordpress-deployment  
  template:
    metadata:
      labels:
        app: wordpress-deployment  
    spec:
      containers:
        - name: wordpress-image
          image: wordpress:latest 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-wordpress 
          volumeMounts:
            - mountPath: /var/www/html 
              name: vol-wordpress
      volumes:
        - name: vol-wordpress 
          persistentVolumeClaim:
            claimName: pvc-wordpress